{{- if .Values.networkPolicies.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  labels:
    {{- include "astronova.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: astronova-backend-netpol
  labels:
    {{- include "astronova.backend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "astronova.backend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    
    - from:
        - podSelector:
            matchLabels:
              {{- include "astronova.frontend.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8000
    
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8000

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: astronova-frontend-netpol
  labels:
    {{- include "astronova.frontend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "astronova.frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:

    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 80
{{- end }}
